### ISSUE TITLE
move release tag

### ISSUE THREAD

**Issue by k-olya** [kparc/k#18]
1.2.0 release tag should point at commit `7d5265c`

**Comment by abalkin** [comment]
Please explain how you determined the right commit.

**Comment by k-olya** [comment]
i compared all recent pull requests and chose the right one

**Comment by k-olya** [comment]
```
npm i "github:kparc/k#7d5265c"
npm i "github:kparc/k#2d3ea5e"
npm i "github:kparc/k#06c6a48"
```
and then `git diff --no-index` between them and the default install

**Comment by abalkin** [comment]
moved v1.2 tag to 7d5265c
